### ISSUE TITLE
[Suggestion] Compat with Nether Depths Upgrade

### ISSUE THREAD

**Issue by TrkvonStpd1e11** [laserman120/Bobble-Detector-Minecraft#1]
Nether Depths Upgrade mod has its own lava bobber, it also has features for lava fishing and nether fishing. Lava fishing rod in NDU mod can be used by Create's Deployer as well, so I think it's a good idea to make lava bobber in NDU mod compat with Bobber Detector for automation.

**Comment by laserman120** [comment]
Adjusted the code to also detect bobbers from other mods as long as they include "bobber" in their entity name.

[The changes are now live with the latest commit. Curseforge should be live soon](https://github.com/laserman120/Bobber-Detector-Minecraft/commit/abbdd179bf00a0270392c4747e9d458606996da0)

This should work for now.

**Note: This has been changed with 0.1.7 now it uses the custom forge tag "bobber" to track different kinds of fishing bobber entities. If necessary more can be added either by adding them here or on the third party mod side**
